### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by bjoernISWG** [MaxToyberman/react-native-ssl-pinning#152]
```
    com.facebook.react.bridge.UnexpectedNativeTypeException: Value for expires cannot be cast from Double to String
        at com.facebook.react.bridge.ReadableNativeMap.checkInstance(Unknown Source:56)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(Unknown Source:4)
        at com.facebook.react.bridge.ReadableNativeMap.getString(Unknown Source:2)
        at com.toyberman.a.b.a(Unknown Source:14)
        at com.toyberman.a.a.a(Unknown Source:6)
        at com.toyberman.a.a.a(Unknown Source:13)
        at com.toyberman.RNSslPinningModule.fetch(Unknown Source:107)
        at java.lang.reflect.Method.invoke(Native Method)

```

**Comment by bjoernISWG** [comment]
I have one Header parameter as as Number "expire: 0" not as a String "expire: '0'"

**Comment by mohdmunaf** [comment]
What's the solve for this?
