### ISSUE TITLE
Unhandled exception from Java module when passing an invalid url

### ISSUE THREAD

**Issue by DPirate** [MaxToyberman/react-native-ssl-pinning#211]
First encountered when I accidentally used an invalid port. The java module throws an unhandled exception causing the app to crash.

case: http://localhost:355055
<img src="https://github.com/user-attachments/assets/30292caf-192f-4e6b-b4f6-9b6707fb6c16" width="200">

case: http://locala/&.com
<img src="https://github.com/user-attachments/assets/55175261-1549-48ee-80c4-c30cf2c22a38" width="200">

Device used: Motog 5g | Android 11

There was no unhandled exception on iOS 17.4 simulator

**Comment by Sophearithz** [comment]
Facing the same issue on android app react native v0.77 ssl-pinning v1.5.8

Exception in native call
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
                                                                                                    	at com.toyberman.RNSslPinningModule.getDomainName(RNSslPinningModule.java:123)
                                                                                                    	at com.toyberman.RNSslPinningModule.fetch(RNSslPinningModule.java:174)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:146)
                                                                                                    	at com.facebook.jni.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
