### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by dimlksin2** [MaxToyberman/react-native-ssl-pinning#68]
Fatal Exception: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
       at com.toyberman.RNSslPinningModule$2.onResponse(RNSslPinningModule.java:211)
       at com.google.firebase.perf.network.zzg.onResponse()
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

  "version": "1.4.5"

**Comment by dimlksin2** [comment]
Galaxy S3 Mini Value Edition
Galaxy Grand Neo

android 4.2.2

**Comment by MaxToyberman** [comment]
@dimlksin2 Version 1.4.6 released today, with a fix. let me know if you still have issues
